name: invoice-extraction

services:

  api:
    container_name: invoice-api
    build:
      context: ./src
      dockerfile: ./InvoiceApi/Dockerfile
    ports:
      - 5120:8080

  ollama:
    container_name: ollama
    image: ollama/ollama
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - 11434:11434
